FROM debian:stable-slim

ARG chrome_url

ENV CHROME_URL=$chrome_url

RUN apt-get update && apt-get install -qy \
        wget fonts-freefont-ttf \
     --no-install-recommends \
    && wget -O chrome-stable.deb "${CHROME_URL}" -q --progress=bar  \
    && apt install -qqy ./chrome-stable.deb \
    && rm chrome-stable.deb \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get autoremove -y

RUN useradd headless --shell /bin/bash --create-home \
  && usermod -a -G sudo headless \
  && echo 'ALL ALL = (ALL) NOPASSWD: ALL' >> /etc/sudoers \
  && echo 'headless:nopassword' | chpasswd

RUN google-chrome --version

RUN mkdir /data && chown -R headless:headless /data

USER headless

ENTRYPOINT google-chrome --disable-gpu --headless --allow-running-insecure-content --ignore-certificate-errors --remote-debugging-address=0.0.0.0 --remote-debugging-port=9222 --user-data-dir=/data
